=== kpmg-agile/ca-pqvp/raml/api/v1/images/image.schema.json
{
    "id": "http://kpmg/webstart/Image",
    "type": "object",
    "$schema": "http://json-schema.org/draft-04/schema",
    "required": ["imageId"],
    "additionalProperties": false,
    "properties": {
        "imageId": {
            "description": "The identifier of the object",
            "type": "string"
        },
        "productId": {
            "description": "ProductId of the associated product",
            "type": "string"
        },
        "baseUrl": {
            "description": "Root path to the image that will be suffixed to locate small, medium, large images",
            "type": "string"
        },
        "defaultvalue": {
            "description": "Indicates that this image is the default for the productId",
            "type": "boolean"
        }
    }
}

=== kpmg-agile/ca-pqvp/raml/api/v1/images/image-collection.example.json
[
    {
        "imageId": "100",
        "productId": "1",
        "baseUrl": "images/products/product1_iphone6_image1",
        "defaultvalue": true
    },
    {
        "imageId": "101",
        "productId": "1",
        "baseUrl": "images/products/product1_iphone6_image2",
        "defaultvalue": false
    },
    {
        "imageId": "102",
        "productId": "1",
        "baseUrl": "images/products/product1_iphone6_image3",
        "defaultvalue": false
    }
]
